### ISSUE TITLE
int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by betterthanever2** [dunkyl/SlyPyYTDAPI#14]
This is actually about a few issues. 

1. You forgot to remove `print` statement on line 595 of the `ytdapi.py`
2. I'm getting `int() argument must be a string, a bytes-like object or a real number, not 'NoneType'` on some of the updates. I checked: my code does not use explicit conversion to integers.
3. I'm getting `'NoneType' object has no attribute 'endswith'` on some other updates. Same thing: I'm not using this expression in the code.

**Comment by dunkyl** [comment]
In your environment, do you get the stack trace with your errors? This is helpful, since in this case it would let us know which assumptions about the API that I made were wrong. If you can read them, it also means you don't really have to check whose code does what.

**Comment by betterthanever2** [comment]
```
Traceback (most recent call last):
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 249, in update_target
    target_updates = await target.fetch_target_updates()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 63, in fetch_target_updates
    raw_videos = await self.ytb_api.videos([u.id for u in uploads], parts=Part.ALL_PUBLIC())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyAPI\asyncy.py", line 56, in _items
    return [t async for t in self.gen]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyAPI\asyncy.py", line 56, in <listcomp>
    return [t async for t in self.gen]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 592, in x
    async for v in self.paginated(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyAPI\asyncy.py", line 64, in <genexpr>
    return AsyncLazy(f(x) async for x in self)
                     ^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 594, in <lambda>
    ).map(lambda r: Video(r, self)):
                    ^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 370, in __init__
    yt_date(stream.get('scheduledStartTime')),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 84, in yt_date
    if date.endswith('Z'):
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by betterthanever2** [comment]
```
Traceback (most recent call last):
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 249, in update_target
    target_updates = await target.fetch_target_updates()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\bases\wapaganda\media\platforms\youtube.py", line 63, in fetch_target_updates
    raw_videos = await self.ytb_api.videos([u.id for u in uploads], parts=Part.ALL_PUBLIC())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyAPI\asyncy.py", line 56, in _items
    return [t async for t in self.gen]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyAPI\asyncy.py", line 56, in <listcomp>
    return [t async for t in self.gen]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 592, in x
    async for v in self.paginated(
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyAPI\asyncy.py", line 64, in <genexpr>
    return AsyncLazy(f(x) async for x in self)
                     ^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 594, in <lambda>
    ).map(lambda r: Video(r, self)):
                    ^^^^^^^^^^^^^^
  File "D:\up\code\wapatools\.venv\Lib\site-packages\SlyYTDAPI\ytdapi.py", line 363, in __init__
    self.comment_count = int(statistics.get('commentCount'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by dunkyl** [comment]
Thank you, a new version has been published to address this.
